### ISSUE TITLE
不支持微信开放平台吗？

### ISSUE THREAD

**Issue by yfeng** [feng19/wechat#4]
想在网页端通过微信登录

**Comment by feng19** [comment]
我之前实践过，方案如下：

1. 可以使用 Phoenix + LiveView 开一个页面，render 一个 二维码，二维码内容为url，url需带上唯一标识，url指向 授权页面
2. 微信 扫码打开 授权页面，完成授权之后 通过 唯一标识 pubsub 发送 【微信用户信息】 到 1 页面的 LiveView
